### ISSUE TITLE
[Feature] Allow latest version to be installed with uv

### ISSUE THREAD

**Issue by nathanchenseanwalter** [CAREamics/careamics#464]
## Problem
UV can't install the latest version of careamics right now. It's left at 0.0.01. I have to do uv pip install instead of uv add

**Comment by jdeschamps** [comment]
Hi @nathanchenseanwalter,

Thanks for reporting it! We don't really have experience with `uv`, but we can have a look.

Can you describe your setup? Do you have a `uv` project with a `pyproject.toml` that declares a dependency on `careamics`? Could you post your `pyproject.toml`? Do you have a lock file in your project? That way we can try to reproduce the issue.

I don't know how `uv add` resolves the dependency for careamics, but it does work differently than`uv pip` (see [here](https://github.com/astral-sh/uv/issues/9219#issuecomment-2485573603)).

**Comment by mese79** [comment]
Hi @nathanchenseanwalter !  
I'm not very familiar with `uv`, but I gave it a try and it seems working with the latest `careamics` (`0.0.11`).  
Here are my steps (probably you don't need to do all steps, maybe just `uv add careamics` is enough):  
- `uv init careamics_project`
- `cd careamics_project`
- `uv python install 3.10`
- To install pytorch, I followed this [guide](https://docs.astral.sh/uv/guides/integration/pytorch/#using-a-pytorch-index) and added dependencies to my `pyproject.toml` file (I installed the *cpu* version):
```toml
[project]
name = "careamics-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch>=2.5",
    "torchvision>=0.20",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu" },
]
torchvision = [
    { index = "pytorch-cpu" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
```
- Next is to sync it by `uv sync`
- `uv add careamics-portfolio` (to work with careamics examples)
- `uv add jupyterlab`
- Finally `uv add careamics`

This is my `pyproject.toml` after installation:
```toml
[project]
name = "careamics-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "careamics>=0.0.11",
    "careamics-portfolio>=0.0.15",
    "jupyterlab>=4.4.2",
    "torch>=2.5",
    "torchvision>=0.20",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu" },
]
torchvision = [
    { index = "pytorch-cpu" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
```

And I was able to import `careamics` and run examples in *jupyter*:
```bash
uv run --with jupyter jupyter lab
```

Please try these steps and see if it works for you as well.  
Also, please describe your steps and the problem in more detail so we can understand it better and provide more help.
